
ratings_means <- c('likable','interesting','sad','happy')
hsv_means <- c('hue','saturation','brightness')
hsv_full <- c(hsv_means,'before_diag','before_susp','target')
metadata_means <- c('comment_count','like_count','has_filter')
face_means <- c('has_face','face_ct')


vars <- list(
  ig=list(
    post=list( 
      ratings_means=ratings_means,
      hsv_means=hsv_means,
      hsv_full=c(hsv_means,'before_diag','before_susp','target'),
      metadata_means=metadata_means,
      face_means=face_means,
      all_ig_means=c(hsv_means,metadata_means),
      ig_face_means=c(hsv_means, metadata_means, face_means),
      all_means=c(ratings_means,hsv_means,metadata_means,face_means),
      full=c(ratings_means, hsv_means,metadata_means,
             'likable.var','interesting.var','sad.var','happy.var',
             'before_diag','before_susp','target')
    ),
    username=list(
      ratings_means=ratings_means,
      hsv_means=hsv_means,
      hsv_full=c(hsv_means,'before_diag','before_susp','target'),
      metadata_means=c(metadata_means,'url'),
      face_means=face_means,
      all_ig_means=c(hsv_means,metadata_means,'url'),
      ig_face_means=c(hsv_means, metadata_means, 'url', face_means),
      all_means=c(ratings_means,hsv_means,metadata_means,'url',face_means),
      full=c(ratings_means, hsv_means,metadata_means,'url', face_means,
             'likable.var','interesting.var','sad.var','happy.var',
             'one_word','description','target')
    ),
    created_date=list(
      ratings_means=ratings_means,
      hsv_means=hsv_means,
      hsv_full=c(hsv_means,'before_diag','before_susp','target'),
      metadata_means=c(metadata_means,'url'),
      face_means=face_means,
      all_ig_means=c(hsv_means,metadata_means,'url'),
      ig_face_means=c(hsv_means, metadata_means, 'url', face_means),
      all_means=c(ratings_means,hsv_means,metadata_means,'url',face_means),
      full=c(ratings_means, hsv_means,metadata_means,'url', face_means,
             'likable.var','interesting.var','sad.var','happy.var',
             'one_word','description','target')
    )
  ),
  tw=list(
    weekly=list( 
      all_means=c('total_words',
              'LIWC_num_words', 'LIWC_happs', 'LabMT_num_words', 'LabMT_happs',
              'ANEW_num_words', 'ANEW_happs', 'ANEW_arousal', 'ANEW_dominance',
              'LIWC_total_count', 'LIWC_funct', 'LIWC_pronoun', 'LIWC_ppron',
              'LIWC_i', 'LIWC_we', 'LIWC_you', 'LIWC_shehe', 'LIWC_they',
              'LIWC_ipron', 'LIWC_article', 'LIWC_verb', 'LIWC_auxverb',
              'LIWC_past', 'LIWC_present', 'LIWC_future', 'LIWC_adverb',
              'LIWC_preps', 'LIWC_conj', 'LIWC_negate', 'LIWC_quant',
              'LIWC_number', 'LIWC_swear', 'LIWC_social', 'LIWC_family',
              'LIWC_friend', 'LIWC_humans', 'LIWC_affect', 'LIWC_posemo',
              'LIWC_negemo', 'LIWC_anx', 'LIWC_anger', 'LIWC_sad', 'LIWC_cogmech',
              'LIWC_insight', 'LIWC_cause', 'LIWC_discrep', 'LIWC_tentat',
              'LIWC_certain', 'LIWC_inhib', 'LIWC_incl', 'LIWC_excl',
              'LIWC_percept', 'LIWC_see', 'LIWC_hear', 'LIWC_feel', 'LIWC_bio',
              'LIWC_body', 'LIWC_health', 'LIWC_sexual', 'LIWC_ingest',
              'LIWC_relativ', 'LIWC_motion', 'LIWC_space', 'LIWC_time',
              'LIWC_work', 'LIWC_achieve', 'LIWC_leisure', 'LIWC_home',
              'LIWC_money', 'LIWC_relig', 'LIWC_death', 'LIWC_assent',
              'LIWC_nonfl', 'tweet_count', 'word_count', 'has_url',
              'is_rt', 'is_reply'),
      no_addtl_means=c('total_words',
                       'LIWC_num_words', 'LIWC_happs', 'LabMT_num_words', 'LabMT_happs',
                       'ANEW_num_words', 'ANEW_happs', 'ANEW_arousal', 'ANEW_dominance',
                       'LIWC_total_count', 'LIWC_funct', 'LIWC_pronoun', 'LIWC_ppron',
                       'LIWC_i', 'LIWC_we', 'LIWC_you', 'LIWC_shehe', 'LIWC_they',
                       'LIWC_ipron', 'LIWC_article', 'LIWC_verb', 'LIWC_auxverb',
                       'LIWC_past', 'LIWC_present', 'LIWC_future', 'LIWC_adverb',
                       'LIWC_preps', 'LIWC_conj', 'LIWC_negate', 'LIWC_quant',
                       'LIWC_number', 'LIWC_swear', 'LIWC_social', 'LIWC_family',
                       'LIWC_friend', 'LIWC_humans', 'LIWC_affect', 'LIWC_posemo',
                       'LIWC_negemo', 'LIWC_anx', 'LIWC_anger', 'LIWC_sad', 'LIWC_cogmech',
                       'LIWC_insight', 'LIWC_cause', 'LIWC_discrep', 'LIWC_tentat',
                       'LIWC_certain', 'LIWC_inhib', 'LIWC_incl', 'LIWC_excl',
                       'LIWC_percept', 'LIWC_see', 'LIWC_hear', 'LIWC_feel', 'LIWC_bio',
                       'LIWC_body', 'LIWC_health', 'LIWC_sexual', 'LIWC_ingest',
                       'LIWC_relativ', 'LIWC_motion', 'LIWC_space', 'LIWC_time',
                       'LIWC_work', 'LIWC_achieve', 'LIWC_leisure', 'LIWC_home',
                       'LIWC_money', 'LIWC_relig', 'LIWC_death', 'LIWC_assent',
                       'LIWC_nonfl', 'tweet_count', 'word_count', 'has_url',
                       'is_rt', 'is_reply'),
      model=c('total_words',
              'LIWC_num_words', 'LIWC_happs', 'LabMT_num_words', 'LabMT_happs',
              'ANEW_num_words', 'ANEW_happs', 'ANEW_arousal', 'ANEW_dominance',
              'LIWC_total_count', 'LIWC_funct', 'LIWC_pronoun', 'LIWC_ppron',
              'LIWC_i', 'LIWC_we', 'LIWC_you', 'LIWC_shehe', 'LIWC_they',
              'LIWC_ipron', 'LIWC_article', 'LIWC_verb', 'LIWC_auxverb',
              'LIWC_past', 'LIWC_present', 'LIWC_future', 'LIWC_adverb',
              'LIWC_preps', 'LIWC_conj', 'LIWC_negate', 'LIWC_quant',
              'LIWC_number', 'LIWC_swear', 'LIWC_social', 'LIWC_family',
              'LIWC_friend', 'LIWC_humans', 'LIWC_affect', 'LIWC_posemo',
              'LIWC_negemo', 'LIWC_anx', 'LIWC_anger', 'LIWC_sad', 'LIWC_cogmech',
              'LIWC_insight', 'LIWC_cause', 'LIWC_discrep', 'LIWC_tentat',
              'LIWC_certain', 'LIWC_inhib', 'LIWC_incl', 'LIWC_excl',
              'LIWC_percept', 'LIWC_see', 'LIWC_hear', 'LIWC_feel', 'LIWC_bio',
              'LIWC_body', 'LIWC_health', 'LIWC_sexual', 'LIWC_ingest',
              'LIWC_relativ', 'LIWC_motion', 'LIWC_space', 'LIWC_time',
              'LIWC_work', 'LIWC_achieve', 'LIWC_leisure', 'LIWC_home',
              'LIWC_money', 'LIWC_relig', 'LIWC_death', 'LIWC_assent',
              'LIWC_nonfl', 'tweet_count', 'word_count', 'has_url',
              'is_rt', 'is_reply'),
      full=c('tweet_id', 'user_id', 'total_words',
             'LIWC_num_words', 'LIWC_happs', 'LabMT_num_words', 'LabMT_happs',
             'ANEW_num_words', 'ANEW_happs', 'ANEW_arousal', 'ANEW_dominance',
             'LIWC_total_count', 'LIWC_funct', 'LIWC_pronoun', 'LIWC_ppron',
             'LIWC_i', 'LIWC_we', 'LIWC_you', 'LIWC_shehe', 'LIWC_they',
             'LIWC_ipron', 'LIWC_article', 'LIWC_verb', 'LIWC_auxverb',
             'LIWC_past', 'LIWC_present', 'LIWC_future', 'LIWC_adverb',
             'LIWC_preps', 'LIWC_conj', 'LIWC_negate', 'LIWC_quant',
             'LIWC_number', 'LIWC_swear', 'LIWC_social', 'LIWC_family',
             'LIWC_friend', 'LIWC_humans', 'LIWC_affect', 'LIWC_posemo',
             'LIWC_negemo', 'LIWC_anx', 'LIWC_anger', 'LIWC_sad', 'LIWC_cogmech',
             'LIWC_insight', 'LIWC_cause', 'LIWC_discrep', 'LIWC_tentat',
             'LIWC_certain', 'LIWC_inhib', 'LIWC_incl', 'LIWC_excl',
             'LIWC_percept', 'LIWC_see', 'LIWC_hear', 'LIWC_feel', 'LIWC_bio',
             'LIWC_body', 'LIWC_health', 'LIWC_sexual', 'LIWC_ingest',
             'LIWC_relativ', 'LIWC_motion', 'LIWC_space', 'LIWC_time',
             'LIWC_work', 'LIWC_achieve', 'LIWC_leisure', 'LIWC_home',
             'LIWC_money', 'LIWC_relig', 'LIWC_death', 'LIWC_assent',
             'LIWC_nonfl', 'time_unit', 'tweet_count', 'word_count', 'has_url',
             'is_rt', 'is_reply', 'target','before_diag','before_susp',
             'created_date','diag_date')
    ),
    user_id=list(
      all_means=c('LIWC_happs', 'LabMT_happs',
              'ANEW_happs', 'ANEW_arousal', 'ANEW_dominance',
              'LIWC_total_count', 'LIWC_funct', 'LIWC_pronoun', 'LIWC_ppron',
              'LIWC_i', 'LIWC_we', 'LIWC_you', 'LIWC_shehe', 'LIWC_they',
              'LIWC_ipron', 'LIWC_article', 'LIWC_verb', 'LIWC_auxverb',
              'LIWC_past', 'LIWC_present', 'LIWC_future', 'LIWC_adverb',
              'LIWC_preps', 'LIWC_conj', 'LIWC_negate', 'LIWC_quant',
              'LIWC_number', 'LIWC_swear', 'LIWC_social', 'LIWC_family',
              'LIWC_friend', 'LIWC_humans', 'LIWC_affect', 'LIWC_posemo',
              'LIWC_negemo', 'LIWC_anx', 'LIWC_anger', 'LIWC_sad', 'LIWC_cogmech',
              'LIWC_insight', 'LIWC_cause', 'LIWC_discrep', 'LIWC_tentat',
              'LIWC_certain', 'LIWC_inhib', 'LIWC_incl', 'LIWC_excl',
              'LIWC_percept', 'LIWC_see', 'LIWC_hear', 'LIWC_feel', 'LIWC_bio',
              'LIWC_body', 'LIWC_health', 'LIWC_sexual', 'LIWC_ingest',
              'LIWC_relativ', 'LIWC_motion', 'LIWC_space', 'LIWC_time',
              'LIWC_work', 'LIWC_achieve', 'LIWC_leisure', 'LIWC_home',
              'LIWC_money', 'LIWC_relig', 'LIWC_death', 'LIWC_assent',
              'LIWC_nonfl', 'tweet_count', 'word_count', 'has_url',
              'is_rt', 'is_reply'),
      no_addtl_means=c('LIWC_happs', 'LabMT_happs',
                       'ANEW_happs', 'ANEW_arousal', 'ANEW_dominance',
                       'LIWC_total_count', 'LIWC_funct', 'LIWC_pronoun', 'LIWC_ppron',
                       'LIWC_i', 'LIWC_we', 'LIWC_you', 'LIWC_shehe', 'LIWC_they',
                       'LIWC_ipron', 'LIWC_article', 'LIWC_verb', 'LIWC_auxverb',
                       'LIWC_past', 'LIWC_present', 'LIWC_future', 'LIWC_adverb',
                       'LIWC_preps', 'LIWC_conj', 'LIWC_negate', 'LIWC_quant',
                       'LIWC_number', 'LIWC_swear', 'LIWC_social', 'LIWC_family',
                       'LIWC_friend', 'LIWC_humans', 'LIWC_affect', 'LIWC_posemo',
                       'LIWC_negemo', 'LIWC_anx', 'LIWC_anger', 'LIWC_sad', 'LIWC_cogmech',
                       'LIWC_insight', 'LIWC_cause', 'LIWC_discrep', 'LIWC_tentat',
                       'LIWC_certain', 'LIWC_inhib', 'LIWC_incl', 'LIWC_excl',
                       'LIWC_percept', 'LIWC_see', 'LIWC_hear', 'LIWC_feel', 'LIWC_bio',
                       'LIWC_body', 'LIWC_health', 'LIWC_sexual', 'LIWC_ingest',
                       'LIWC_relativ', 'LIWC_motion', 'LIWC_space', 'LIWC_time',
                       'LIWC_work', 'LIWC_achieve', 'LIWC_leisure', 'LIWC_home',
                       'LIWC_money', 'LIWC_relig', 'LIWC_death', 'LIWC_assent',
                       'LIWC_nonfl', 'tweet_count', 'word_count', 'has_url',
                       'is_rt', 'is_reply'),
      model=c('LIWC_happs', 'LabMT_happs',
              'ANEW_happs', 'ANEW_arousal', 'ANEW_dominance',
              'LIWC_funct', 'LIWC_pronoun', 'LIWC_ppron',
              'LIWC_i', 'LIWC_we', 'LIWC_you', 'LIWC_shehe', 'LIWC_they',
              'LIWC_ipron', 'LIWC_article', 'LIWC_verb', 'LIWC_auxverb',
              'LIWC_past', 'LIWC_present', 'LIWC_future', 'LIWC_adverb',
              'LIWC_preps', 'LIWC_conj', 'LIWC_negate', 'LIWC_quant',
              'LIWC_number', 'LIWC_swear', 'LIWC_social', 'LIWC_family',
              'LIWC_friend', 'LIWC_humans', 'LIWC_affect', 'LIWC_posemo',
              'LIWC_negemo', 'LIWC_anx', 'LIWC_anger', 'LIWC_sad', 'LIWC_cogmech',
              'LIWC_insight', 'LIWC_cause', 'LIWC_discrep', 'LIWC_tentat',
              'LIWC_certain', 'LIWC_inhib', 'LIWC_incl', 'LIWC_excl',
              'LIWC_percept', 'LIWC_see', 'LIWC_hear', 'LIWC_feel', 'LIWC_bio',
              'LIWC_body', 'LIWC_health', 'LIWC_sexual', 'LIWC_ingest',
              'LIWC_relativ', 'LIWC_motion', 'LIWC_space', 'LIWC_time',
              'LIWC_work', 'LIWC_achieve', 'LIWC_leisure', 'LIWC_home',
              'LIWC_money', 'LIWC_relig', 'LIWC_death', 'LIWC_assent',
              'LIWC_nonfl', 'word_count', 'has_url',
              'is_rt', 'is_reply'),
      full=c('tweet_id', 'user_id', 
             'LIWC_happs', 'LabMT_happs',
             'ANEW_happs', 'ANEW_arousal', 'ANEW_dominance',
             'LIWC_total_count', 'LIWC_funct', 'LIWC_pronoun', 'LIWC_ppron',
             'LIWC_i', 'LIWC_we', 'LIWC_you', 'LIWC_shehe', 'LIWC_they',
             'LIWC_ipron', 'LIWC_article', 'LIWC_verb', 'LIWC_auxverb',
             'LIWC_past', 'LIWC_present', 'LIWC_future', 'LIWC_adverb',
             'LIWC_preps', 'LIWC_conj', 'LIWC_negate', 'LIWC_quant',
             'LIWC_number', 'LIWC_swear', 'LIWC_social', 'LIWC_family',
             'LIWC_friend', 'LIWC_humans', 'LIWC_affect', 'LIWC_posemo',
             'LIWC_negemo', 'LIWC_anx', 'LIWC_anger', 'LIWC_sad', 'LIWC_cogmech',
             'LIWC_insight', 'LIWC_cause', 'LIWC_discrep', 'LIWC_tentat',
             'LIWC_certain', 'LIWC_inhib', 'LIWC_incl', 'LIWC_excl',
             'LIWC_percept', 'LIWC_see', 'LIWC_hear', 'LIWC_feel', 'LIWC_bio',
             'LIWC_body', 'LIWC_health', 'LIWC_sexual', 'LIWC_ingest',
             'LIWC_relativ', 'LIWC_motion', 'LIWC_space', 'LIWC_time',
             'LIWC_work', 'LIWC_achieve', 'LIWC_leisure', 'LIWC_home',
             'LIWC_money', 'LIWC_relig', 'LIWC_death', 'LIWC_assent',
             'LIWC_nonfl', 'time_unit', 'tweet_count', 'word_count', 'has_url',
             'is_rt', 'is_reply', 'target'),
      created_date=list(
        all_means=c('total_words','LIWC_num_words', 'LIWC_happs', 'LabMT_num_words', 'LabMT_happs',
                'ANEW_num_words', 'ANEW_happs', 'ANEW_arousal', 'ANEW_dominance',
                'LIWC_total_count', 'LIWC_funct', 'LIWC_pronoun', 'LIWC_ppron',
                'LIWC_i', 'LIWC_we', 'LIWC_you', 'LIWC_shehe', 'LIWC_they',
                'LIWC_ipron', 'LIWC_article', 'LIWC_verb', 'LIWC_auxverb',
                'LIWC_past', 'LIWC_present', 'LIWC_future', 'LIWC_adverb',
                'LIWC_preps', 'LIWC_conj', 'LIWC_negate', 'LIWC_quant',
                'LIWC_number', 'LIWC_swear', 'LIWC_social', 'LIWC_family',
                'LIWC_friend', 'LIWC_humans', 'LIWC_affect', 'LIWC_posemo',
                'LIWC_negemo', 'LIWC_anx', 'LIWC_anger', 'LIWC_sad', 'LIWC_cogmech',
                'LIWC_insight', 'LIWC_cause', 'LIWC_discrep', 'LIWC_tentat',
                'LIWC_certain', 'LIWC_inhib', 'LIWC_incl', 'LIWC_excl',
                'LIWC_percept', 'LIWC_see', 'LIWC_hear', 'LIWC_feel', 'LIWC_bio',
                'LIWC_body', 'LIWC_health', 'LIWC_sexual', 'LIWC_ingest',
                'LIWC_relativ', 'LIWC_motion', 'LIWC_space', 'LIWC_time',
                'LIWC_work', 'LIWC_achieve', 'LIWC_leisure', 'LIWC_home',
                'LIWC_money', 'LIWC_relig', 'LIWC_death', 'LIWC_assent',
                'LIWC_nonfl', 'tweet_count', 'word_count', 'has_url',
                'is_rt', 'is_reply'),
        no_addtl_means=c('total_words','LIWC_num_words', 'LIWC_happs', 'LabMT_num_words', 'LabMT_happs',
                         'ANEW_num_words', 'ANEW_happs', 'ANEW_arousal', 'ANEW_dominance',
                         'LIWC_total_count', 'LIWC_funct', 'LIWC_pronoun', 'LIWC_ppron',
                         'LIWC_i', 'LIWC_we', 'LIWC_you', 'LIWC_shehe', 'LIWC_they',
                         'LIWC_ipron', 'LIWC_article', 'LIWC_verb', 'LIWC_auxverb',
                         'LIWC_past', 'LIWC_present', 'LIWC_future', 'LIWC_adverb',
                         'LIWC_preps', 'LIWC_conj', 'LIWC_negate', 'LIWC_quant',
                         'LIWC_number', 'LIWC_swear', 'LIWC_social', 'LIWC_family',
                         'LIWC_friend', 'LIWC_humans', 'LIWC_affect', 'LIWC_posemo',
                         'LIWC_negemo', 'LIWC_anx', 'LIWC_anger', 'LIWC_sad', 'LIWC_cogmech',
                         'LIWC_insight', 'LIWC_cause', 'LIWC_discrep', 'LIWC_tentat',
                         'LIWC_certain', 'LIWC_inhib', 'LIWC_incl', 'LIWC_excl',
                         'LIWC_percept', 'LIWC_see', 'LIWC_hear', 'LIWC_feel', 'LIWC_bio',
                         'LIWC_body', 'LIWC_health', 'LIWC_sexual', 'LIWC_ingest',
                         'LIWC_relativ', 'LIWC_motion', 'LIWC_space', 'LIWC_time',
                         'LIWC_work', 'LIWC_achieve', 'LIWC_leisure', 'LIWC_home',
                         'LIWC_money', 'LIWC_relig', 'LIWC_death', 'LIWC_assent',
                         'LIWC_nonfl', 'tweet_count', 'word_count', 'has_url',
                         'is_rt', 'is_reply'),
        model=c('total_words','LIWC_num_words', 'LIWC_happs', 'LabMT_num_words', 'LabMT_happs',
                'ANEW_num_words', 'ANEW_happs', 'ANEW_arousal', 'ANEW_dominance',
                'LIWC_total_count', 'LIWC_funct', 'LIWC_pronoun', 'LIWC_ppron',
                'LIWC_i', 'LIWC_we', 'LIWC_you', 'LIWC_shehe', 'LIWC_they',
                'LIWC_ipron', 'LIWC_article', 'LIWC_verb', 'LIWC_auxverb',
                'LIWC_past', 'LIWC_present', 'LIWC_future', 'LIWC_adverb',
                'LIWC_preps', 'LIWC_conj', 'LIWC_negate', 'LIWC_quant',
                'LIWC_number', 'LIWC_swear', 'LIWC_social', 'LIWC_family',
                'LIWC_friend', 'LIWC_humans', 'LIWC_affect', 'LIWC_posemo',
                'LIWC_negemo', 'LIWC_anx', 'LIWC_anger', 'LIWC_sad', 'LIWC_cogmech',
                'LIWC_insight', 'LIWC_cause', 'LIWC_discrep', 'LIWC_tentat',
                'LIWC_certain', 'LIWC_inhib', 'LIWC_incl', 'LIWC_excl',
                'LIWC_percept', 'LIWC_see', 'LIWC_hear', 'LIWC_feel', 'LIWC_bio',
                'LIWC_body', 'LIWC_health', 'LIWC_sexual', 'LIWC_ingest',
                'LIWC_relativ', 'LIWC_motion', 'LIWC_space', 'LIWC_time',
                'LIWC_work', 'LIWC_achieve', 'LIWC_leisure', 'LIWC_home',
                'LIWC_money', 'LIWC_relig', 'LIWC_death', 'LIWC_assent',
                'LIWC_nonfl', 'tweet_count', 'word_count', 'has_url',
                'is_rt', 'is_reply'),
        full=c('tweet_id', 'user_id', 'total_words',
               'LIWC_num_words', 'LIWC_happs', 'LabMT_num_words', 'LabMT_happs',
               'ANEW_num_words', 'ANEW_happs', 'ANEW_arousal', 'ANEW_dominance',
               'LIWC_total_count', 'LIWC_funct', 'LIWC_pronoun', 'LIWC_ppron',
               'LIWC_i', 'LIWC_we', 'LIWC_you', 'LIWC_shehe', 'LIWC_they',
               'LIWC_ipron', 'LIWC_article', 'LIWC_verb', 'LIWC_auxverb',
               'LIWC_past', 'LIWC_present', 'LIWC_future', 'LIWC_adverb',
               'LIWC_preps', 'LIWC_conj', 'LIWC_negate', 'LIWC_quant',
               'LIWC_number', 'LIWC_swear', 'LIWC_social', 'LIWC_family',
               'LIWC_friend', 'LIWC_humans', 'LIWC_affect', 'LIWC_posemo',
               'LIWC_negemo', 'LIWC_anx', 'LIWC_anger', 'LIWC_sad', 'LIWC_cogmech',
               'LIWC_insight', 'LIWC_cause', 'LIWC_discrep', 'LIWC_tentat',
               'LIWC_certain', 'LIWC_inhib', 'LIWC_incl', 'LIWC_excl',
               'LIWC_percept', 'LIWC_see', 'LIWC_hear', 'LIWC_feel', 'LIWC_bio',
               'LIWC_body', 'LIWC_health', 'LIWC_sexual', 'LIWC_ingest',
               'LIWC_relativ', 'LIWC_motion', 'LIWC_space', 'LIWC_time',
               'LIWC_work', 'LIWC_achieve', 'LIWC_leisure', 'LIWC_home',
               'LIWC_money', 'LIWC_relig', 'LIWC_death', 'LIWC_assent',
               'LIWC_nonfl', 'time_unit', 'tweet_count', 'word_count', 'has_url',
               'is_rt', 'is_reply', 'target','before_diag','before_susp',
               'created_date','diag_date')
      )
    )
  )
)

saveRDS(vars,'varset.rds')
